package co.edu.usc.vision.interacciones.api.dao.model.public;

import co.edu.usc.vision.interacciones.api.dao.model.public.Componentes;
import co.edu.usc.vision.interacciones.api.dao.model.public.ComponentesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComponentesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.componentes
     *
     * @mbggenerated
     */
    int countByExample(ComponentesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.componentes
     *
     * @mbggenerated
     */
    int deleteByExample(ComponentesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.componentes
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String codigoatc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.componentes
     *
     * @mbggenerated
     */
    int insert(Componentes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.componentes
     *
     * @mbggenerated
     */
    int insertSelective(Componentes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.componentes
     *
     * @mbggenerated
     */
    List<Componentes> selectByExample(ComponentesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.componentes
     *
     * @mbggenerated
     */
    Componentes selectByPrimaryKey(String codigoatc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.componentes
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Componentes record, @Param("example") ComponentesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.componentes
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Componentes record, @Param("example") ComponentesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.componentes
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Componentes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.componentes
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Componentes record);
}