package co.edu.usc.vision.interacciones.api.dao.model.public;

import java.io.Serializable;

public class Componentes implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.componentes.codigoatc
     *
     * @mbggenerated
     */
    private String codigoatc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.componentes.categoriapadre
     *
     * @mbggenerated
     */
    private String categoriapadre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.componentes.nombreatc
     *
     * @mbggenerated
     */
    private String nombreatc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.componentes
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.componentes.codigoatc
     *
     * @return the value of public.componentes.codigoatc
     *
     * @mbggenerated
     */
    public String getCodigoatc() {
        return codigoatc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.componentes.codigoatc
     *
     * @param codigoatc the value for public.componentes.codigoatc
     *
     * @mbggenerated
     */
    public void setCodigoatc(String codigoatc) {
        this.codigoatc = codigoatc == null ? null : codigoatc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.componentes.categoriapadre
     *
     * @return the value of public.componentes.categoriapadre
     *
     * @mbggenerated
     */
    public String getCategoriapadre() {
        return categoriapadre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.componentes.categoriapadre
     *
     * @param categoriapadre the value for public.componentes.categoriapadre
     *
     * @mbggenerated
     */
    public void setCategoriapadre(String categoriapadre) {
        this.categoriapadre = categoriapadre == null ? null : categoriapadre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.componentes.nombreatc
     *
     * @return the value of public.componentes.nombreatc
     *
     * @mbggenerated
     */
    public String getNombreatc() {
        return nombreatc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.componentes.nombreatc
     *
     * @param nombreatc the value for public.componentes.nombreatc
     *
     * @mbggenerated
     */
    public void setNombreatc(String nombreatc) {
        this.nombreatc = nombreatc == null ? null : nombreatc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.componentes
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Componentes other = (Componentes) that;
        return (this.getCodigoatc() == null ? other.getCodigoatc() == null : this.getCodigoatc().equals(other.getCodigoatc()))
            && (this.getCategoriapadre() == null ? other.getCategoriapadre() == null : this.getCategoriapadre().equals(other.getCategoriapadre()))
            && (this.getNombreatc() == null ? other.getNombreatc() == null : this.getNombreatc().equals(other.getNombreatc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.componentes
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCodigoatc() == null) ? 0 : getCodigoatc().hashCode());
        result = prime * result + ((getCategoriapadre() == null) ? 0 : getCategoriapadre().hashCode());
        result = prime * result + ((getNombreatc() == null) ? 0 : getNombreatc().hashCode());
        return result;
    }
}