package co.edu.usc.vision.interacciones.api.dao.model.public;

import java.io.Serializable;
import java.math.BigDecimal;

public class Componentesactivos implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.componentesactivos.componentes_codigoatc
     *
     * @mbggenerated
     */
    private String componentesCodigoatc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.componentesactivos.idcodigoinvima
     *
     * @mbggenerated
     */
    private BigDecimal idcodigoinvima;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.componentesactivos
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.componentesactivos.componentes_codigoatc
     *
     * @return the value of public.componentesactivos.componentes_codigoatc
     *
     * @mbggenerated
     */
    public String getComponentesCodigoatc() {
        return componentesCodigoatc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.componentesactivos.componentes_codigoatc
     *
     * @param componentesCodigoatc the value for public.componentesactivos.componentes_codigoatc
     *
     * @mbggenerated
     */
    public void setComponentesCodigoatc(String componentesCodigoatc) {
        this.componentesCodigoatc = componentesCodigoatc == null ? null : componentesCodigoatc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.componentesactivos.idcodigoinvima
     *
     * @return the value of public.componentesactivos.idcodigoinvima
     *
     * @mbggenerated
     */
    public BigDecimal getIdcodigoinvima() {
        return idcodigoinvima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.componentesactivos.idcodigoinvima
     *
     * @param idcodigoinvima the value for public.componentesactivos.idcodigoinvima
     *
     * @mbggenerated
     */
    public void setIdcodigoinvima(BigDecimal idcodigoinvima) {
        this.idcodigoinvima = idcodigoinvima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.componentesactivos
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Componentesactivos other = (Componentesactivos) that;
        return (this.getComponentesCodigoatc() == null ? other.getComponentesCodigoatc() == null : this.getComponentesCodigoatc().equals(other.getComponentesCodigoatc()))
            && (this.getIdcodigoinvima() == null ? other.getIdcodigoinvima() == null : this.getIdcodigoinvima().equals(other.getIdcodigoinvima()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.componentesactivos
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getComponentesCodigoatc() == null) ? 0 : getComponentesCodigoatc().hashCode());
        result = prime * result + ((getIdcodigoinvima() == null) ? 0 : getIdcodigoinvima().hashCode());
        return result;
    }
}