package co.edu.usc.vision.interacciones.api.dao.model.public;

import java.io.Serializable;

public class Drugbank implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.drugbank.drugbank_id
     *
     * @mbggenerated
     */
    private String drugbankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.drugbank.atc
     *
     * @mbggenerated
     */
    private String atc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.drugbank.interaccion
     *
     * @mbggenerated
     */
    private String interaccion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.drugbank
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.drugbank.drugbank_id
     *
     * @return the value of public.drugbank.drugbank_id
     *
     * @mbggenerated
     */
    public String getDrugbankId() {
        return drugbankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.drugbank.drugbank_id
     *
     * @param drugbankId the value for public.drugbank.drugbank_id
     *
     * @mbggenerated
     */
    public void setDrugbankId(String drugbankId) {
        this.drugbankId = drugbankId == null ? null : drugbankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.drugbank.atc
     *
     * @return the value of public.drugbank.atc
     *
     * @mbggenerated
     */
    public String getAtc() {
        return atc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.drugbank.atc
     *
     * @param atc the value for public.drugbank.atc
     *
     * @mbggenerated
     */
    public void setAtc(String atc) {
        this.atc = atc == null ? null : atc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.drugbank.interaccion
     *
     * @return the value of public.drugbank.interaccion
     *
     * @mbggenerated
     */
    public String getInteraccion() {
        return interaccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.drugbank.interaccion
     *
     * @param interaccion the value for public.drugbank.interaccion
     *
     * @mbggenerated
     */
    public void setInteraccion(String interaccion) {
        this.interaccion = interaccion == null ? null : interaccion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.drugbank
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Drugbank other = (Drugbank) that;
        return (this.getDrugbankId() == null ? other.getDrugbankId() == null : this.getDrugbankId().equals(other.getDrugbankId()))
            && (this.getAtc() == null ? other.getAtc() == null : this.getAtc().equals(other.getAtc()))
            && (this.getInteraccion() == null ? other.getInteraccion() == null : this.getInteraccion().equals(other.getInteraccion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.drugbank
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDrugbankId() == null) ? 0 : getDrugbankId().hashCode());
        result = prime * result + ((getAtc() == null) ? 0 : getAtc().hashCode());
        result = prime * result + ((getInteraccion() == null) ? 0 : getInteraccion().hashCode());
        return result;
    }
}