package co.edu.usc.vision.interacciones.api.dao.model;

import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

public interface ProductosPresentacionesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productos_presentaciones
     *
     * @mbggenerated
     */
    int countByExample(ProductosPresentacionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productos_presentaciones
     *
     * @mbggenerated
     */
    int deleteByExample(ProductosPresentacionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productos_presentaciones
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal idcum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productos_presentaciones
     *
     * @mbggenerated
     */
    int insert(ProductosPresentaciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productos_presentaciones
     *
     * @mbggenerated
     */
    int insertSelective(ProductosPresentaciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productos_presentaciones
     *
     * @mbggenerated
     */
    List<ProductosPresentaciones> selectByExample(ProductosPresentacionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productos_presentaciones
     *
     * @mbggenerated
     */
    ProductosPresentaciones selectByPrimaryKey(BigDecimal idcum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productos_presentaciones
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductosPresentaciones record, @Param("example") ProductosPresentacionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productos_presentaciones
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductosPresentaciones record, @Param("example") ProductosPresentacionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productos_presentaciones
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductosPresentaciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productos_presentaciones
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductosPresentaciones record);
}