package co.edu.usc.vision.interacciones.api.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class Registrossanitarios implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registrossanitarios.idcodigoinvima
     *
     * @mbggenerated
     */
    private BigDecimal idcodigoinvima;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registrossanitarios.codigoinvima
     *
     * @mbggenerated
     */
    private String codigoinvima;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registrossanitarios.estado
     *
     * @mbggenerated
     */
    private BigDecimal estado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registrossanitarios.nombre
     *
     * @mbggenerated
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table registrossanitarios
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registrossanitarios.idcodigoinvima
     *
     * @return the value of registrossanitarios.idcodigoinvima
     *
     * @mbggenerated
     */
    public BigDecimal getIdcodigoinvima() {
        return idcodigoinvima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registrossanitarios.idcodigoinvima
     *
     * @param idcodigoinvima the value for registrossanitarios.idcodigoinvima
     *
     * @mbggenerated
     */
    public void setIdcodigoinvima(BigDecimal idcodigoinvima) {
        this.idcodigoinvima = idcodigoinvima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registrossanitarios.codigoinvima
     *
     * @return the value of registrossanitarios.codigoinvima
     *
     * @mbggenerated
     */
    public String getCodigoinvima() {
        return codigoinvima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registrossanitarios.codigoinvima
     *
     * @param codigoinvima the value for registrossanitarios.codigoinvima
     *
     * @mbggenerated
     */
    public void setCodigoinvima(String codigoinvima) {
        this.codigoinvima = codigoinvima == null ? null : codigoinvima.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registrossanitarios.estado
     *
     * @return the value of registrossanitarios.estado
     *
     * @mbggenerated
     */
    public BigDecimal getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registrossanitarios.estado
     *
     * @param estado the value for registrossanitarios.estado
     *
     * @mbggenerated
     */
    public void setEstado(BigDecimal estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registrossanitarios.nombre
     *
     * @return the value of registrossanitarios.nombre
     *
     * @mbggenerated
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registrossanitarios.nombre
     *
     * @param nombre the value for registrossanitarios.nombre
     *
     * @mbggenerated
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registrossanitarios
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Registrossanitarios other = (Registrossanitarios) that;
        return (this.getIdcodigoinvima() == null ? other.getIdcodigoinvima() == null : this.getIdcodigoinvima().equals(other.getIdcodigoinvima()))
            && (this.getCodigoinvima() == null ? other.getCodigoinvima() == null : this.getCodigoinvima().equals(other.getCodigoinvima()))
            && (this.getEstado() == null ? other.getEstado() == null : this.getEstado().equals(other.getEstado()))
            && (this.getNombre() == null ? other.getNombre() == null : this.getNombre().equals(other.getNombre()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registrossanitarios
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdcodigoinvima() == null) ? 0 : getIdcodigoinvima().hashCode());
        result = prime * result + ((getCodigoinvima() == null) ? 0 : getCodigoinvima().hashCode());
        result = prime * result + ((getEstado() == null) ? 0 : getEstado().hashCode());
        result = prime * result + ((getNombre() == null) ? 0 : getNombre().hashCode());
        return result;
    }
}