package co.edu.usc.vision.interacciones.api.dao.model;

import java.io.Serializable;

public class Unidadesmedida implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unidadesmedida.abreviatura
     *
     * @mbggenerated
     */
    private String abreviatura;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unidadesmedida.nombre
     *
     * @mbggenerated
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unidadesmedida
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unidadesmedida.abreviatura
     *
     * @return the value of unidadesmedida.abreviatura
     *
     * @mbggenerated
     */
    public String getAbreviatura() {
        return abreviatura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unidadesmedida.abreviatura
     *
     * @param abreviatura the value for unidadesmedida.abreviatura
     *
     * @mbggenerated
     */
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura == null ? null : abreviatura.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unidadesmedida.nombre
     *
     * @return the value of unidadesmedida.nombre
     *
     * @mbggenerated
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unidadesmedida.nombre
     *
     * @param nombre the value for unidadesmedida.nombre
     *
     * @mbggenerated
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unidadesmedida
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Unidadesmedida other = (Unidadesmedida) that;
        return (this.getAbreviatura() == null ? other.getAbreviatura() == null : this.getAbreviatura().equals(other.getAbreviatura()))
            && (this.getNombre() == null ? other.getNombre() == null : this.getNombre().equals(other.getNombre()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unidadesmedida
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAbreviatura() == null) ? 0 : getAbreviatura().hashCode());
        result = prime * result + ((getNombre() == null) ? 0 : getNombre().hashCode());
        return result;
    }
}